apiVersion: v1
kind: ServiceAccount
metadata:
  name: aviation-pipeline-sa
  namespace: aviation-pipeline
  annotations:
    # Workload Identity — maps to the GCP SA created in gke.tf
    iam.gke.io/gcp-service-account: aviation-pipeline-sa@gcp-lakehouseproject.iam.gserviceaccount.com
